version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 3.1
  build:
    commands:
      - echo "CD into source folder, because my source code is tidy"  
      - cd ValuesAPI
      - echo "Restore, Build, then Publish.."
      - dotnet restore
      - dotnet build --no-restore
      - dotnet publish -c release -o ./build_output
artifacts:  
  files:
    - build_output/**/*
    - ServerlessTemplate.yml
