version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore ValuesAPI/ValuesAPI.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output ValuesAPI/ValuesAPI.csproj
artifacts:
  files:
    - ValuesAPI/build_output/**/*
    - scripts/**/*
    - appspec.yml
    - ServerlessTemplate.yml
