version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore AWSServerlessApp/AWSServerlessApp.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output AWSServerlessApp/AWSServerlessApp.csproj
artifacts:
  files:
    - AWSServerlessApp/build_output/**/*
    - scripts/**/*
    - appspec.yml