version: 0.2
env:
  variables:
    S3_BUCKET: severless-app-demo
    REGION: ap-south-1
phases:
  build:
    commands:
      - echo "Packaging CloudFormation nested stacks.."
      - aws cloudformation package --region $REGION --template-file ServerlessTemplate.yml --s3-bucket $S3_BUCKET --output-template-file ServerlessTemplate.yml
      - echo "Done."
artifacts:
  files:
    - ServerlessTemplate.yml    
