version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`      
      - dotnet restore ValuesAPI/ValuesAPI.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release
artifacts:
  files:
    - ValuesAPI/bin/release/netcoreapp3.1/publish/**/*
    - scripts/**/*
    - appspec.yml
    - ServerlessTemplate.yml
