AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Application that uses the ASP.NET Core framework running in Amazon Lambda
Resources:
  AspNetCoreLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: ValuesAPI::ValuesAPI.LambdaEntryPoint::FunctionHandlerAsync
      Runtime: dotnetcore3.1
      CodeUri: 's3://severless-app-demo/ValuesAPI.zip'
      MemorySize: 256
      Timeout: 30        
      Events:
        ValuesAPI:
          Type: Api
          Properties:
            Path: /api/values
            Method: get
      Environment:
        Variables:
          REGION: ap-south-1
